export const states = [
  {
    name: 'Alabama',
    abbreviation: 'AL',
  },
  {
    name: 'Alaska',
    abbreviation: 'AK',
  },
  {
    name: 'American Samoa',
    abbreviation: 'AS',
  },
  {
    name: 'Arizona',
    abbreviation: 'AZ',
  },
  {
    name: 'Arkansas',
    abbreviation: 'AR',
  },
  {
    name: 'California',
    abbreviation: 'CA',
  },
  {
    name: 'Colorado',
    abbreviation: 'CO',
  },
  {
    name: 'Connecticut',
    abbreviation: 'CT',
  },
  {
    name: 'Delaware',
    abbreviation: 'DE',
  },
  {
    name: 'District Of Columbia',
    abbreviation: 'DC',
  },
  {
    name: 'Federated States Of Micronesia',
    abbreviation: 'FM',
  },
  {
    name: 'Florida',
    abbreviation: 'FL',
  },
  {
    name: 'Georgia',
    abbreviation: 'GA',
  },
  {
    name: 'Guam',
    abbreviation: 'GU',
  },
  {
    name: 'Hawaii',
    abbreviation: 'HI',
  },
  {
    name: 'Idaho',
    abbreviation: 'ID',
  },
  {
    name: 'Illinois',
    abbreviation: 'IL',
  },
  {
    name: 'Indiana',
    abbreviation: 'IN',
  },
  {
    name: 'Iowa',
    abbreviation: 'IA',
  },
  {
    name: 'Kansas',
    abbreviation: 'KS',
  },
  {
    name: 'Kentucky',
    abbreviation: 'KY',
  },
  {
    name: 'Louisiana',
    abbreviation: 'LA',
  },
  {
    name: 'Maine',
    abbreviation: 'ME',
  },
  {
    name: 'Marshall Islands',
    abbreviation: 'MH',
  },
  {
    name: 'Maryland',
    abbreviation: 'MD',
  },
  {
    name: 'Massachusetts',
    abbreviation: 'MA',
  },
  {
    name: 'Michigan',
    abbreviation: 'MI',
  },
  {
    name: 'Minnesota',
    abbreviation: 'MN',
  },
  {
    name: 'Mississippi',
    abbreviation: 'MS',
  },
  {
    name: 'Missouri',
    abbreviation: 'MO',
  },
  {
    name: 'Montana',
    abbreviation: 'MT',
  },
  {
    name: 'Nebraska',
    abbreviation: 'NE',
  },
  {
    name: 'Nevada',
    abbreviation: 'NV',
  },
  {
    name: 'New Hampshire',
    abbreviation: 'NH',
  },
  {
    name: 'New Jersey',
    abbreviation: 'NJ',
  },
  {
    name: 'New Mexico',
    abbreviation: 'NM',
  },
  {
    name: 'New York',
    abbreviation: 'NY',
  },
  {
    name: 'North Carolina',
    abbreviation: 'NC',
  },
  {
    name: 'North Dakota',
    abbreviation: 'ND',
  },
  {
    name: 'Northern Mariana Islands',
    abbreviation: 'MP',
  },
  {
    name: 'Ohio',
    abbreviation: 'OH',
  },
  {
    name: 'Oklahoma',
    abbreviation: 'OK',
  },
  {
    name: 'Oregon',
    abbreviation: 'OR',
  },
  {
    name: 'Palau',
    abbreviation: 'PW',
  },
  {
    name: 'Pennsylvania',
    abbreviation: 'PA',
  },
  {
    name: 'Puerto Rico',
    abbreviation: 'PR',
  },
  {
    name: 'Rhode Island',
    abbreviation: 'RI',
  },
  {
    name: 'South Carolina',
    abbreviation: 'SC',
  },
  {
    name: 'South Dakota',
    abbreviation: 'SD',
  },
  {
    name: 'Tennessee',
    abbreviation: 'TN',
  },
  {
    name: 'Texas',
    abbreviation: 'TX',
  },
  {
    name: 'Utah',
    abbreviation: 'UT',
  },
  {
    name: 'Vermont',
    abbreviation: 'VT',
  },
  {
    name: 'Virgin Islands',
    abbreviation: 'VI',
  },
  {
    name: 'Virginia',
    abbreviation: 'VA',
  },
  {
    name: 'Washington',
    abbreviation: 'WA',
  },
  {
    name: 'West Virginia',
    abbreviation: 'WV',
  },
  {
    name: 'Wisconsin',
    abbreviation: 'WI',
  },
  {
    name: 'Wyoming',
    abbreviation: 'WY',
  },
];

export const people = [
  {
    id: 1,
    first_name: 'Juana',
    last_name: 'Belfitt',
    email: 'jbelfitt0@umn.edu',
    gender: 'Agender',
  },
  {
    id: 2,
    first_name: 'Viole',
    last_name: 'Corbishley',
    email: 'vcorbishley1@aol.com',
    gender: 'Male',
  },
  {
    id: 3,
    first_name: 'Felix',
    last_name: 'Oxenford',
    email: 'foxenford2@vkontakte.ru',
    gender: 'Bigender',
  },
  {
    id: 4,
    first_name: 'Myrtia',
    last_name: 'Van Der Weedenburg',
    email: 'mvanderweedenburg3@huffingtonpost.com',
    gender: 'Male',
  },
  {
    id: 5,
    first_name: 'Langston',
    last_name: 'Flaherty',
    email: 'lflaherty4@apple.com',
    gender: 'Polygender',
  },
  {
    id: 6,
    first_name: 'Maureene',
    last_name: 'Wither',
    email: 'mwither5@merriam-webster.com',
    gender: 'Bigender',
  },
  {
    id: 7,
    first_name: 'Zia',
    last_name: 'Ellacombe',
    email: 'zellacombe6@deviantart.com',
    gender: 'Polygender',
  },
  {
    id: 8,
    first_name: 'Cathleen',
    last_name: 'Connerly',
    email: 'cconnerly7@barnesandnoble.com',
    gender: 'Bigender',
  },
  {
    id: 9,
    first_name: 'Lorie',
    last_name: 'Shank',
    email: 'lshank8@usa.gov',
    gender: 'Genderqueer',
  },
  {
    id: 10,
    first_name: 'My',
    last_name: 'Riddeough',
    email: 'mriddeough9@icq.com',
    gender: 'Polygender',
  },
  {
    id: 11,
    first_name: 'Vaughn',
    last_name: 'Huertas',
    email: 'vhuertasa@creativecommons.org',
    gender: 'Polygender',
  },
  {
    id: 12,
    first_name: 'Christean',
    last_name: 'Jeroch',
    email: 'cjerochb@technorati.com',
    gender: 'Genderqueer',
  },
  {
    id: 13,
    first_name: 'Dorothee',
    last_name: "O'Flannery",
    email: 'doflanneryc@vk.com',
    gender: 'Non-binary',
  },
  {
    id: 14,
    first_name: 'Denice',
    last_name: 'Spikins',
    email: 'dspikinsd@seesaa.net',
    gender: 'Genderfluid',
  },
  {
    id: 15,
    first_name: 'Adelaide',
    last_name: 'Evequot',
    email: 'aevequote@wordpress.org',
    gender: 'Non-binary',
  },
  {
    id: 16,
    first_name: 'Callean',
    last_name: 'Gaunter',
    email: 'cgaunterf@state.tx.us',
    gender: 'Genderfluid',
  },
  {
    id: 17,
    first_name: 'Durand',
    last_name: 'Cay',
    email: 'dcayg@phoca.cz',
    gender: 'Non-binary',
  },
  {
    id: 18,
    first_name: 'Devondra',
    last_name: 'Jauncey',
    email: 'djaunceyh@state.tx.us',
    gender: 'Male',
  },
  {
    id: 19,
    first_name: 'Tomas',
    last_name: 'Winsley',
    email: 'twinsleyi@ca.gov',
    gender: 'Male',
  },
  {
    id: 20,
    first_name: 'Cristabel',
    last_name: 'Dearnaly',
    email: 'cdearnalyj@nyu.edu',
    gender: 'Female',
  },
  {
    id: 21,
    first_name: 'Briney',
    last_name: 'Forstall',
    email: 'bforstallk@nationalgeographic.com',
    gender: 'Polygender',
  },
  {
    id: 22,
    first_name: 'Orelia',
    last_name: 'Rassell',
    email: 'orasselll@reuters.com',
    gender: 'Agender',
  },
  {
    id: 23,
    first_name: 'Leslie',
    last_name: 'Ketch',
    email: 'lketchm@acquirethisname.com',
    gender: 'Genderfluid',
  },
  {
    id: 24,
    first_name: 'Cristobal',
    last_name: 'Sancto',
    email: 'csancton@forbes.com',
    gender: 'Non-binary',
  },
  {
    id: 25,
    first_name: 'Carrol',
    last_name: 'Dymoke',
    email: 'cdymokeo@vk.com',
    gender: 'Agender',
  },
  {
    id: 26,
    first_name: 'Sibyl',
    last_name: 'Morbey',
    email: 'smorbeyp@theglobeandmail.com',
    gender: 'Non-binary',
  },
  {
    id: 27,
    first_name: 'Marvin',
    last_name: 'Albrook',
    email: 'malbrookq@google.cn',
    gender: 'Female',
  },
  {
    id: 28,
    first_name: 'Hanna',
    last_name: 'Valance',
    email: 'hvalancer@smugmug.com',
    gender: 'Female',
  },
  {
    id: 29,
    first_name: 'Penn',
    last_name: 'Heggs',
    email: 'pheggss@arizona.edu',
    gender: 'Agender',
  },
  {
    id: 30,
    first_name: 'Aura',
    last_name: 'Matushevich',
    email: 'amatushevicht@cbslocal.com',
    gender: 'Genderfluid',
  },
  {
    id: 31,
    first_name: 'Noemi',
    last_name: 'Brabon',
    email: 'nbrabonu@de.vu',
    gender: 'Bigender',
  },
  {
    id: 32,
    first_name: 'Bailie',
    last_name: 'Oxtiby',
    email: 'boxtibyv@phoca.cz',
    gender: 'Genderqueer',
  },
  {
    id: 33,
    first_name: 'Tara',
    last_name: 'Snasel',
    email: 'tsnaselw@lycos.com',
    gender: 'Non-binary',
  },
  {
    id: 34,
    first_name: 'Jody',
    last_name: 'Barrass',
    email: 'jbarrassx@hugedomains.com',
    gender: 'Bigender',
  },
  {
    id: 35,
    first_name: 'Pablo',
    last_name: 'Kerton',
    email: 'pkertony@dmoz.org',
    gender: 'Genderqueer',
  },
  {
    id: 36,
    first_name: 'Pen',
    last_name: 'Pimlett',
    email: 'ppimlettz@yellowbook.com',
    gender: 'Agender',
  },
  {
    id: 37,
    first_name: 'Carmelita',
    last_name: 'Rowan',
    email: 'crowan10@umich.edu',
    gender: 'Non-binary',
  },
  {
    id: 38,
    first_name: 'Grady',
    last_name: 'Boichat',
    email: 'gboichat11@amazon.co.uk',
    gender: 'Genderqueer',
  },
  {
    id: 39,
    first_name: 'Corny',
    last_name: 'Patullo',
    email: 'cpatullo12@simplemachines.org',
    gender: 'Agender',
  },
  {
    id: 40,
    first_name: 'Catherine',
    last_name: 'Chitham',
    email: 'cchitham13@sbwire.com',
    gender: 'Agender',
  },
  {
    id: 41,
    first_name: 'Anatole',
    last_name: 'Fabbri',
    email: 'afabbri14@yahoo.com',
    gender: 'Polygender',
  },
  {
    id: 42,
    first_name: 'Celinka',
    last_name: 'Marchent',
    email: 'cmarchent15@ebay.com',
    gender: 'Female',
  },
  {
    id: 43,
    first_name: 'Silvia',
    last_name: 'Ouldred',
    email: 'souldred16@facebook.com',
    gender: 'Genderqueer',
  },
  {
    id: 44,
    first_name: 'Daveen',
    last_name: 'Chat',
    email: 'dchat17@miitbeian.gov.cn',
    gender: 'Genderfluid',
  },
  {
    id: 45,
    first_name: 'Brade',
    last_name: 'Cosbee',
    email: 'bcosbee18@netlog.com',
    gender: 'Male',
  },
  {
    id: 46,
    first_name: 'Lutero',
    last_name: 'Turmel',
    email: 'lturmel19@squidoo.com',
    gender: 'Polygender',
  },
  {
    id: 47,
    first_name: 'Rickey',
    last_name: 'Davis',
    email: 'rdavis1a@biblegateway.com',
    gender: 'Agender',
  },
  {
    id: 48,
    first_name: 'Vinnie',
    last_name: 'Brodbin',
    email: 'vbrodbin1b@ow.ly',
    gender: 'Agender',
  },
  {
    id: 49,
    first_name: 'Irving',
    last_name: 'Clell',
    email: 'iclell1c@imdb.com',
    gender: 'Genderfluid',
  },
  {
    id: 50,
    first_name: 'Morton',
    last_name: 'Stidson',
    email: 'mstidson1d@devhub.com',
    gender: 'Female',
  },
];
